### ISSUE TITLE
Input de cep não permite zero à esquerda

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin-marketplace#100]
Atualmente os inputs para inserção de cep no admin marketplace não permitem inserir zero à esquerda, ou seja, se você tenta salvar 00000000, ele muda e salva 10000, se tentar 01000000, ele muda e salva 1000000. Ou seja, o zero antes de qualquer número, ele não permite salvar e se cadastrar como nulo, ou seja, apenas com limite máximo, ele não considera aquele nulo como zero.

**Comment by leomp12** [comment]
Isto é só nas regras de envio, certo? Ele salva como número e o mínimo está como 10000 na maioria dos admin settings dos apps.
Não há CEP menor que 10000 (o menor na verdade é 1000000) no Brasil, portanto 10000 no início do range é a mesma coisa que só ter limite final, 0 ou 10000 no limite inicial não faz diferença.

**Comment by leomp12** [comment]
Acho que o ideal é ter um componente específico para o objeto `zip_range`, neste caso o valor mostrado será um string formatada ainda que os fields do objeto (geralmente `min` e `max`) sejam números.
Como não é um limitador (já que de fato não há CEP menor que 10000) mas é uma melhoria de UX, vamos deixar como _enhancement_.

**Comment by matheusgnreis** [comment]
Pior que existe sim CEP menor que 10000, em São Paulo, a faixa de cep corresponde por 01000-000 a 19999-999, logo não é possível criar uma regra de frete por exemplo para o estado do sudeste inteiro, pois o certo seria colocar de 01000-000 até 39999-999, mas acaba pegando só 10000-000 até 39999-999

**Comment by talissonf** [comment]
@matheusgnreis enquanto não rola esse enhancement eu vou criar essa regra direto no hidden_data do app pro lojista que informou. Você olhar pra mim pra qual faixa de cep ele quer criar as regras?

**Comment by matheusgnreis** [comment]
@talissonf na verdade ai o leo está correto, porque ele salva 7 dígitos e como o correio está batendo 8, então acaba sendo 01000-000, valeu pelo pronto atendimento ai
