### ISSUE TITLE
Input de data gerando data errada

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin-marketplace#124]
Criando cupom e brinde que foram os testes, como input deve ser o mesmo, estou colocando aqui só o de brinde. Abaixo eu coloco a data 15/09/2020 00:00:00 até 15/09/2020 23:59:59, conforme mostra a imagem:

![Captura de tela de 2020-09-15 12-57-53](https://user-images.githubusercontent.com/35343551/93235165-90171700-f753-11ea-8d36-d04a4564529d.png)

No PATCH do network já vemos as informações enviadas como erradas.
![Captura de tela de 2020-09-15 12-57-41](https://user-images.githubusercontent.com/35343551/93235171-90afad80-f753-11ea-97a6-3bf1beb6be1d.png)

Abaixo vemos apenas a confirmação do erro.
![Captura de tela de 2020-09-15 12-58-35](https://user-images.githubusercontent.com/35343551/93235157-8db4bd00-f753-11ea-8326-ed82096611ec.png)

Com 1 mês para frente, isso deve ter passado batido porque o mês 1, deve ser considerado como 0, como no exemplo:

```
new Date(2020, 0, 6)
```
Gera a data como janeiro, então a solução deve ser simples

**Comment by leomp12** [comment]
@matheusgnreis não entendi a segunda mensagem.
Já está considerando o mês começando com zero [aqui](https://github.com/ecomplus/admin-marketplace/blob/master/src/components/_inputs/js/InputDate.js#L49), nos meus testes ficou tudo certo, mês e hora...

![Screenshot_2020-09-21 E-Com Plus Dashboard App](https://user-images.githubusercontent.com/10326572/93807417-f81ca000-fc20-11ea-95c7-aa718a82e825.png)

```json
{"freebies_rules":[{"date_range":{"end":"2020-12-01T03:00:00.000Z","start":"2020-11-13T03:00:00.000Z"},"label":"Dia do cliente","product_ids":["5c768e21c626be23430d5086"],"min_subtotal":1000},{"date_range":{"start":"2020-10-15T03:00:00.000Z","end":"2020-10-16T02:59:59.000Z"},"product_ids":["5cdf0e8f887ef430f1f6d0a7"],"label":"teste novo","min_subtotal":100}]}
```

**Comment by matheusgnreis** [comment]
Apague o tempo de inicio por exemplo, e depois coloque 23:59:59 e salve

**Comment by leomp12** [comment]
@matheusgnreis deu normal também...

![Screenshot_2020-09-21 E-Com Plus Dashboard App(1)](https://user-images.githubusercontent.com/10326572/93808027-d5d75200-fc21-11ea-98b4-9f6bd846b1fe.png)

```json
{"freebies_rules":[{"date_range":{"end":"2020-12-01T03:00:00.000Z","start":"2020-11-14T02:59:59.000Z"},"label":"Dia do cliente","product_ids":["5c768e21c626be23430d5086"],"min_subtotal":1000},{"date_range":{"start":"2020-10-15T03:00:00.000Z","end":"2020-10-16T02:59:59.000Z"},"product_ids":["5cdf0e8f887ef430f1f6d0a7"],"label":"teste novo","min_subtotal":100}]}
```

**Comment by leomp12** [comment]
Inclusive o _teste novo_ que você criou também tá correspondendo certo:

```json
{"start":"2020-10-15T03:00:00.000Z","end":"2020-10-16T02:59:59.000Z"}
```

![Screenshot_2020-09-21 E-Com Plus Dashboard App(2)](https://user-images.githubusercontent.com/10326572/93808294-2e0e5400-fc22-11ea-9e37-88aa41ac0171.png)

**Comment by matheusgnreis** [comment]
Teste com setembro, veja:
![Captura de tela de 2020-09-21 15-53-40](https://user-images.githubusercontent.com/35343551/93808822-e5a36600-fc22-11ea-9cfb-2f256ae3c982.png)

Olha o PATCH, com data de outubro
![Captura de tela de 2020-09-21 15-54-52](https://user-images.githubusercontent.com/35343551/93808818-e4723900-fc22-11ea-92bc-624b38243be7.png)

Isso na criação de uma nova regra. Não na edição

**Comment by matheusgnreis** [comment]
Nesse caso aqui, peguei uma que estava com tempo 00:00:00
![Captura de tela de 2020-09-21 16-05-40](https://user-images.githubusercontent.com/35343551/93810288-ca395a80-fc24-11ea-94c3-108264e3b59b.png)

Apaguei tudo e coloquei de novo 23:59:59
![Captura de tela de 2020-09-21 16-08-55](https://user-images.githubusercontent.com/35343551/93810351-e6d59280-fc24-11ea-8019-2f2c51166513.png)
E o ano de inicio 1900

Testei tanto no local e no painel

**Comment by matheusgnreis** [comment]
no local do admin marketplace, quando apago as horas, dá lá que a data é inválida e gera essa outra ai, dai quando eu coloco a hora, ele apenas edita a hora deixando esse data nova gerada

**Comment by leomp12** [comment]
Testei criando e deu errado mesmo, tanto local quanto no https://app.e-com.plus/ , mas o erro não era por causa do input, o valor emitido pelo input sempre esterve certo.
Tinha algum objeto nos arrays no data do app com formato inválido, não cheguei a olhar qual era, aí tava dando um erro falando que o componente esperara um array e recebia um objeto, limpei tudo que estava lá e depois criei novamente aí funcionou normal.
Tenta aí, se funcionar tem que descobrir é como chegou a ser salvo errado isso aí, não parece ser um problema dos inputs de data e hora não...
