### ISSUE TITLE
Não é possível instalar aplicativo por celular

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin-marketplace#129]
Em teste, um lojista tentou notificações inteligentes, depois tentei o mesmo app no celular e não funcionou. Após tentar no pc funcionou. Depois testei o app pagar.me no celular e não funcionou, logo constando o problema de instalação pelo celular

**Comment by ThaisChaves** [comment]
Tentei instalar hoje e deu certo. Instalei os 2 citados pelo Matheus, mais e-mails transacionais, wirecard (que abre um pop up) e deu certinho.

**Comment by leomp12** [comment]
Valeu @ThaisChaves
