### ISSUE TITLE
Minimizar seções de app 

### ISSUE THREAD

**Issue by vitorrgg** [ecomplus/admin-marketplace#137]
Após atualização no _admin-marketplace_ não é mais possível minimizar as seções de configuração dos apps. Isso atrapalha um pouco a usabilidade em apps com seções longas, como o caso do _discounts_

**Comment by leomp12** [comment]
É o collapse..

**Comment by thiagoabreudev** [comment]
https://github.com/ecomplus/admin-marketplace/pull/144
