### ISSUE TITLE
Ao instalar aplicativos de redirecionar para autenticação, nada ocorre

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin-marketplace#154]
Ao tentar instalar Pagseguro ou Wirecard, que deveria me direcionar para Wirecard ou Pagseguro, mas não está ocorrendo isso, apenas instala o aplicativo

**Comment by leomp12** [comment]
Uai mas demoraram bem pra ver esse bug em...

**Comment by matheusgnreis** [comment]
Deve ser, o Wesley da tia sonia instalou, achei que tinha sido recente, mas foi no fim de janeiro que tentou e deu certo.
