### ISSUE TITLE
Erros ao salvar dados após modificação

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin-marketplace#157]
A resposta que tive é:

{"status":400,"error_code":8129998,"message":"Bad-formatted JSON body, details in user_message","user_message":{"en_us":"data should NOT have less than 1 properties","pt_br":"data não deve ter menos que 1 propriedade"},"more_info":"/applications/schema/data.json"}

Já ocorreu em mais de um aplicativo. O data está indo vazio quando a alteração é no hidden_data por exemplo e ai dá esse erro, porque precisa ter algo.

**Comment by leomp12** [comment]
Na verdade se a alteração é no `hidden_data` nem era pra salvar nada em `data`, não era pra ter essa requisição...
O `hidden_data` foi salvo corretamente né?

**Comment by matheusgnreis** [comment]
Foi salvo, mas aparece o aviso na tela, falando que deu erro. Com certeza alguém vai achar que deu problema.

**Comment by matheusgnreis** [comment]
Porque é feito uma requisição pro data e pro hidden_data, mas o data fica vazio e dá erro, como se fosse erro ao salvar

**Comment by leomp12** [comment]
Sim sim, não deixou de ser um erro, só pra saber onde procurar e o que fixar.

**Comment by matheusgnreis** [comment]
@leomp12 erro voltando a ocorrer, me relataram aqui, foi tentado realizar uma exportação de produto para o Bling, editando somente o hidden_data e gerando o erro:

![data-problem](https://user-images.githubusercontent.com/35343551/112684299-951af880-8e51-11eb-83d6-9b840edc0df7.png)

**Comment by leomp12** [comment]
Uai @matheusgnreis , na verdade o app do Bling joga importação na fila do `data` mesmo (não no `hidden_data`), então ele não deveria estar vazio não, isso não é o app velho do Bling não né?

**Comment by matheusgnreis** [comment]
Não, ele é novo mesmo. Acabei de testar, não está indo nem pra exportação então. O produto na verdade, já até foi exportado anteriormente automaticamente, o erro está rolando, a versão dele .11 e a mais nova é .12, isso modifica?

**Comment by leomp12** [comment]
Não faz diferença a versão...
Você viu que o input agora é uma busca por nome/SKU do produto?
Se botar o ID direto agora acho que não está funcionando.

Em seg., 29 de mar. de 2021 11:01, Matheus Reis ***@***.***>
escreveu:

**Comment by matheusgnreis** [comment]
![Screenshot (71)](https://user-images.githubusercontent.com/35343551/112851206-23c18c80-9081-11eb-81f9-d36a2206e0d6.png)
Label ainda está ID, colocando SKu na exportação dá a mesma coisa, nada no data

**Comment by leomp12** [comment]
É, isso ainda não foi corrigido direitinho, e não testei o SKU realmente.
Vou dar uma revisada nesse input hoje mais tarde, vai digitando o nome do produto que vai aparecer o autocomplete e vai funcionar.

**Comment by matheusgnreis** [comment]
Sim, eu vi aqui que só funciona se digitar o nome do produto
