### ISSUE TITLE
Erro ao instalar aplicativo

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin-marketplace#161]
Ao instalar aplicativo está ficando carregamento infinito, funcionando somente se recarregar a página.
Testei Gerencianet, Bling, Jadlog e todos deram mesmo erro, então deve ser geral

**Comment by matheusgnreis** [comment]
Pelos testes gerais que estou fazendo, vi que ele realiza o POST, gera o ID do aplicativo, mas fica aquele overlay como se tivesse um processo ocorrendo e não te permite fazer mais nada, só atualizando a página

**Comment by leomp12** [comment]
Na verdade o erro aqui é do router do admin, no marketplace isolado não tem esse erro.

**Comment by leomp12** [comment]
Vou fixar no https://github.com/ecomplus/admin
