### ISSUE TITLE
Input money não válida números inteiros

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin-marketplace#162]
Hoje não existe aviso para min_amount, então se a loja colocar ele como float, dará erro no checkout, por isso é necessário avisar, caso coloque float ao inves de interger

**Comment by leomp12** [comment]
Não tem relação direta com `min_amount` (ou qualquer outra campo específico), a não ser que o problema seja realmente só com esse campo, aí seria um erro do app no admin settings (quando olhei pareceu certo).

**Comment by leomp12** [comment]
Na verdade é porque é input money 😐 
Ele de fato não está checando se deve ser integer.

**Comment by matheusgnreis** [comment]
**data.available_extra_discount.min_amount should be integer**

O campo de valor mínimo da regra de desconto é type text, o mesmo type do campo de desconto concedido e nesse último eu coloco 399,90 e o campo valida normalmente no checkout, já o valor mínimo não.

No brinde, ele é type number e não permite colocar float, informa que deve ser inteiro, só que no brinde a propriedade é min_subtotal, já na regra de desconto a propriedade é min_amount

**Comment by matheusgnreis** [comment]
Isso mesmo kkk, enquanto ia responder aqui, você viu ai

**Comment by matheusgnreis** [comment]
No caso do input money do desconto, ele funciona para decimal e deve ser assim né. Porque tem lojista que dá cupom de desconto com mesmo valor do produto que foi vendido, não tinha em estoque e grande parte das vezes é decimal.
