### ISSUE TITLE
Erro: informações cadastradas não aparecendo

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin-marketplace#168]
No app frete personalizado, mostra as configurações feitas, mas ao abrir o app, não mostra nada, como se estivesse vazio:
![image](https://user-images.githubusercontent.com/35343551/119890943-cc1f9000-bf0e-11eb-8709-9dd6b4e02c32.png)
Veja no network:

![image](https://user-images.githubusercontent.com/35343551/119891014-e3f71400-bf0e-11eb-932e-3e64adb9146d.png)

**Comment by leomp12** [comment]
Isso tá em `hidden_data`, você conferiu no `admin_settings` se esse field tá com `hide: true`?

**Comment by matheusgnreis** [comment]
Não vi nenhum campo hide: true, aparentemente não tem nenhuma propriedade com esse nome lá. Esse teste é da 1011, mas outros informaram isso também.

**Comment by leomp12** [comment]
Cada field do admin settings (conforme a [referência](https://developers.e-com.plus/docs/api/#/store/applications/)) é hidden ou não, não é que existe um campo de configuração `hide`.
O problema aí é justamente que o `hide` não tá definido como true (como deveria no caso desse campo no app), não é um bug do marketplace.
