### ISSUE TITLE
toggle input type

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin-marketplace#190]
If is input type password, must be an icon to click to change type password to text

**Comment by leomp12** [comment]
Pra quê exatamente?

Em sáb., 11 de set. de 2021 17:03, Matheus Reis ***@***.***>
escreveu:

**Comment by leomp12** [comment]
Tem um input de exemplo onde isso seria importante?

Em sáb., 11 de set. de 2021 17:24, Leonardo Matos ***@***.***>
escreveu:

**Comment by matheusgnreis** [comment]
Os inputs com type password. Loja que coloca o token, não consegue ver mais o token que inseriu pra conferir se está certo
