### ISSUE TITLE
Valores default do schema não são salvos no data do app

### ISSUE THREAD

**Issue by talissonf** [ecomplus/admin-marketplace#98]
Ja havia reportado anteriormente que booleanos que estão setados como default no schema do admin_setttings não eram salvos no data do app ao menos que fossem alterados. Porém acontece com qualquer tipo, string, number, etc..

**Comment by leomp12** [comment]
Sim, é um bug já conhecido, de fato em qualquer tipo de input.
Você quer tentar resolvê-lo @talissonf ?
Por enquanto lidamos com isto considerando os padrões no source do app, se o field estiver vazio e tiver um `default`, este `default` deve ser considerado...

**Comment by talissonf** [comment]
> Sim, é um bug já conhecido, de fato em qualquer tipo de input.
> Você quer tentar resolvê-lo @talissonf ?

Hoje não

> Por enquanto lidamos com isto considerando os padrões no source do app, se o field estiver vazio e tiver um `default`, este `default` deve ser considerado...

Não entendi :thinking:

**Comment by leomp12** [comment]
Pensei numa coisa aqui, acho que vou resolver já de uma vez.
